version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    rules:
    - linters:
        - staticcheck
      text: 'SA1019: "sigs.k8s.io/cluster-api/api/core/v1beta1" is deprecated: .*'
    - linters:
        - staticcheck
      text: "QF1001: could apply De Morgan's law"
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  imports:
    alias:
      - pkg: github.com/openshift/assisted-service/api/v1beta1
        alias: aiv1beta1
      - pkg: sigs.k8s.io/cluster-api/api/core/v1beta2
        alias: clusterv1
      - pkg: github.com/openshift-assisted/cluster-api-provider-openshift-assisted/bootstrap/api/v1alpha2
        alias: bootstrapv1alpha2
      - pkg: github.com/openshift-assisted/cluster-api-provider-openshift-assisted/controlplane/api/v1alpha3
        alias: controlplanev1alpha3
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
