version: "2"

run:
  timeout: 5m

linters:
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1001"
        - "-ST1003"
        - "-ST1005"
        - "-ST1008"
        - "-ST1016"
        - "-ST1019"
        - "-ST1023"
        - "-QF1001"
        - "-QF1003"
        - "-QF1008"
        - "-QF1011"

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll

formatters:
  enable:
    - gofmt
    - goimports
