version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1001"
        - "-ST1003"
        - "-ST1005"
        - "-ST1008"
        - "-ST1016"
        - "-ST1019"
        - "-ST1020"
        - "-ST1021"
        - "-ST1023"
        - "-QF1001"
        - "-QF1003"
        - "-QF1008"
        - "-QF1011"

  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
