---
name: Fast Forward Branch

on:
  push:
    branches:
      - master

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: backplane-2.9

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Attempt fast-forward $TARGET_BRANCH to master
        run: |
          git checkout "${TARGET_BRANCH}"
          git merge --ff-only origin/master
          git push origin "${TARGET_BRANCH}"
